### ISSUE TITLE
Interracial relationships still considered taboo?

### ISSUE THREAD

**Issue by Dennywuh** [adhesivecheese/kinklist#5]
Hi @adhesivecheese:

I've just come across the KinkList and was very surprised to find _Interracial_ in the **Taboo** section.

Really? In 2020? Please, move it to Roleplay where it belongs.

Other than that, great work. Thanks in advance,

RutabagaDude

**Comment by adhesivecheese** [comment]
Hi there! Okay so - It's important to point out that I grabbed these lists from an older version of the kinklist, and changed as little as possible in the actual lists for continuity's sake.

Aside from that, though - I'd argue it is in the correct place; wanting to sleep with someone **because** their skin is a different color from yours - essentially fetishising someone because of their race - is a thing I would hope **would be** taboo in 2021. You're not the first one to take another meaning from the placement of that option, though, so it's a thing that's going to be changed as part of the next improvement to the generator, whenever I've got time for it.

**Comment by Dennywuh** [comment]
Hi @adhesivecheese:

Thank you for replying. I understand the aversion to changing an item's location because of data persistence, and I applaud your intention of changing it in future versions of the KinkList.

Regarding your justification, I'm afraid it doesn't stand up to scrutiny. The other issues in the Taboo section are universally accepted as wrong, forbidden or immoral. Interracial relations aren't and shouldn't be classified as if they were.

Your explanation is akin to "Black people like chicken" not being racist because the only people capable of saying it sincerely believe it isn't.

RutabagaDude
